### ISSUE TITLE
KeyError: 'NEWS_API'

### ISSUE THREAD

**Issue by johnfelipe** [ElliottFairhall/Stock-Analysis-Tool#1]
(env) root@template:~/Stock-Analysis-Tool# streamlit run Main.py

	Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

	  You can now view your Streamlit app in your browser.

	  Network URL: http://192.168.20.14:8502
	  External URL: http://181.51.32.154:8502

	2023-12-11 19:49:31.351 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/Stock-Analysis-Tool/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
		exec(code, module.__dict__)
	  File "/root/Stock-Analysis-Tool/Main.py", line 32, in <module>
		News_API = os.environ["NEWS_API"]
	  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
		raise KeyError(key) from None
	KeyError: 'NEWS_API'

**Comment by ElliottFairhall** [comment]
The traceback indicates the app is failing because the required environment variable NEWS_API is not set.

The application expects a News API key to be provided via an environment variable. Before running the app, please define it within a locally created .env file.

I will look to implement something like this in the future:

News_API = os.environ.get("NEWS_API")

if not News_API:
    st.error("Missing NEWS_API environment variable. Please set your News API key.")
    st.stop()
